image: node:latest

stages:
- build
- test

build_job:
  stage: build
  script:
  - npm install
  - npm install -g bower gulp
  - bower install
  - gulp build

test_job:
  stage: test
  script:
  - gulp test --server
  - gulp test --client
