image: node:latest

before_script:
 - npm install
 - npm install -g bower gulp
 - bower install --allow-root

stages:
- build
- test

build_job:
  stage: build
  script:
  - gulp build

test_job:
  stage: test
  script:
  - gulp test --server
  - gulp test --client
